cd ./converted_resource_pack
mv ./pack.png ./pack_icon.png
mv ./assets ./textures
mv ./textures/Minecraft/textures/block ./textures
cd ./textures
mv ./block ./blocks
cd ./blocks
mv ./acacia_door_bottom.png
mv ./acacia_door_top.png
mv ./acacia_leaves.png
mv ./acacia_log_top.png
mv ./acacia_log.png
mv ./acacia_planks.png
mv ./acacia_sapling.png
mv ./activator_rail_on.png
mv ./activator_rail.png
mv ./allium.png
mv ./amethyst_block.png
mv ./amethyst_cluster.png
mv ./ancient_debris_side.png
mv ./ancient_debris_top.png
mv ./andesite.png
mv ./anvil_top.png
mv ./anvil.png
mv ./attached_melon_stem.png
mv ./attached_pumpkin_stem.png
mv ./azalea_plant.png
mv ./azalea_side.png
mv ./azalea_top.png
mv ./azure_bluet.png
mv ./bamboo_block_top.png
mv ./bamboo_block.png
mv ./bamboo_door_top.png
mv ./bamboo_door_bottom.png
mv ./bamboo_fence_particle.png
mv ./bamboo_fence.png
mv ./bamboo_large_leaves.png
mv ./bamboo_mosiac.png
mv ./bamboo_planks.png
mv ./bamboo_singleleaf.png
mv ./bamboo_small_leaves.png
mv ./bamboo_stage0.png
mv ./bamboo_stalk.png
mv ./bamboo_trapdoor.png
mv ./barrel_bottom.png
mv ./barrel_side.png
mv ./barrel_top_open.png
mv ./barrel_top.png
mv ./basalt_side.png
mv ./basalt_top.png
mv ./beacon.png
mv ./bedrock.png
mv ./bee_nest_bottom.png
mv ./bee_nest_front_honey.png
mv ./bee_nest_front.png
mv ./bee_nest_side.png
mv ./bee_nest_top.png
mv ./beehive_end.png
mv ./beehive_front_honey.png
mv ./beehive_front.png
mv ./beehive_side.png
mv beetroots_stage0.png
mv beetroots_stage1.png
mv beetroots_stage2.png
mv beetroots_stage3.png
mv bell_bottom.png
mv bell_side.png
mv bell_top.png
mv ./yellow_wool.png ./wool_colored_yellow
